spring:
  config:
    import: optional:file:./.env[.properties]
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://product-postgres:5434/product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:19090/eureka/
  instance:
    hostname: localhost
    non-secure-port: 19094
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}



server:
  port: ${SERVER_PORT:19094}

